version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: room_design_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: paul
      POSTGRES_DB: room_design_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
